### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by 35niavlys** [fstd/wireshark#1]
Thanks for this repo but can you push a compiled version ?

**Comment by vanfstd** [comment]
Compiled for what platform?

**Comment by fstd** [comment]
Compiled for what platform?

**Comment by 35niavlys** [comment]
At least Linux even if Windows would be best personally...
I will roll up my sleeves if it's not possible but the environment is not really fast to prepare.
The aim is to find a bug with an ARM server

**Comment by fstd** [comment]
Prebuilt releases for Linux usually don't work because a) shared library mismatches and b) static linking issues that glibc introduced.  If you run linux, build from source.  It's not hard.

In the windows world, prebuilt stuff is the way to go, but i have neither a windows build machine nor any interest in finding out just how much of a pain it is to build wireshark on windows.  sorry.

I could offer you a prebuilt release for NetBSD, they got their binary compatibility right :-)

(That all said, note that this whole project isn't finished.  i.e. not all network messages are entirely decoded)

**Comment by 35niavlys** [comment]
yes of course for linux, I'm tired :) I will boot on a VM, it will be quicker
